title: FAIRVault
description: This site will contain FAIRVault documentation.
url: "https://fairvault.github.io"

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

markdown: kramdown
permalink: pretty